alias s-i='systemctl status'
alias s-up='systemctl start'
alias s-r='systemctl restart'
alias s-dw='systemctl stop'
alias s-l='systemctl reload'
alias s-e='systemctl enable'
alias s-d='systemctl disable'
alias ll='ls -la'
